steps:
  - name: Setup Node
    uses: actions/setup-node@v1
    with:
      node-version: 16.x

  - name: Install dependencies
    run: yarn install

  - name: Lint
    run: yarn lint

  - name: Format
    run: yarn format:write && yarn format:check

  - name: Type Check
    run: yarn typecheck

  - name: Test
    run: yarn test:coverage

  - name: Build
    run: yarn build
