name: Main CI/CD Workflow

on:
  pull_request:
    branches: []

jobs:
  server:
    name: Server CI/CD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Trigger Server Workflow
        uses: ./.github/workflows/base.yaml
