name: Base Workflow

on:
  pull_request:
    branches: []

jobs:
  server:
    name: Server Workflow
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format:write && yarn format:check

      - name: Type Check
        run: yarn typecheck

      - name: Test
        run: yarn test:cov

      - name: Build
        run: yarn build
