name: Base Workflow

on:
  pull_request

jobs:
  server:
    name: Server Workflow
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Run Base Server CI
        uses: .github/workflows/base.yml
