name: Main CI/CD Workflow

on: pull_request

jobs:
  server:
    name: Server CI/CD
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.token }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Trigger Server Workflow
        run: |
          cd server
          gh workflow run .github/workflows/base.yml
