name: Main CI/CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

jobs:
  server:
    name: Server CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Trigger Server Workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: |
          cd server
          gh workflow run .github/workflows/base.yml
