name: Base Workflow

on:
  pull_request

jobs:
  server:
    name: Server Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: cd server
        run:  cd server

      - name: Run Base Server CI
        uses: ./.github/workflows/base.yml
