name: Combined Workflow

on:
  push:
    branches:
      - main

jobs:
  server:
    name: Server Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Server CI
        uses: ./server/.github/workflows/ci.yml
